apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-server
spec:
  serviceName: redis-server
  replicas: 3
  template:
    metadata:
      labels:
        app: redis-server
      annotations:
        pod.beta.kubernetes.io/init-containers: '[{
            "name": "k8s-redis-ha-server",
            "image": "tarosky/k8s-redis-ha:server-2.0.0",
            "volumeMounts": [{"name": "opt", "mountPath": "/opt"}]
          }]'
    spec:
      containers:
        - name: redis-server
          image: redis:3.2
          command:
            - /opt/bin/k8s-redis-ha-server
          args:
            - /opt/redis.conf
          env:
            - name: SERVICE
              value: redis-server
            - name: SERVICE_PORT
              value: redis-server
            - name: SENTINEL
              value: redis-sentinel
            - name: SENTINEL_PORT
              value: redis-sentinel
          ports:
            - containerPort: 6379
              name: redis-server
          readinessProbe:
            exec:
              command: ['redis-cli', 'info', 'server']
          volumeMounts:
            - name: redis-server-volume
              mountPath: /data
            - name: opt
              mountPath: /opt
      volumes:
        - name: redis-server-volume
          emptyDir: {}
        - name: opt
          emptyDir: {}
