#!/bin/bash

set -eu

SENTINEL_PASS="_redis-sentinel._tcp.redis-sentinel.${KUBE_NAMESPACE}.svc.cluster.local"

kubectl exec console -n "${KUBE_NAMESPACE}" -- \
  redis-cli \
    -h redis-sentinel \
    -a "${SENTINEL_PASS}" \
    -p 26379 \
    sentinel sentinels mymaster |
    grep '[0-9]\{1,3\}\.'
